### ISSUE TITLE
Can't compile with g++-5 or more

### ISSUE THREAD

**Issue by morispi** [kowallus/PgSA#1]
Hi,

PgSA doesn't compile on a few machines I've tested it on, and that use a version of g++ above 5. I get errors saying that "vector does not name a type".

This seems to come from the fact that two "#include <vector>"s are missing in the files src/index/PgSAIndexInterface.h and src/pseudogenome/readslist/iterator/ReadsListIteratorInterface.h, as adding those #includes resolve the problem.

It however does compile nicely, even without the #include<vector>s, when using older versions of g++ (tested with g++-4.8).

Have you tried and managed to compile with a version of g++ over 5?

**Comment by kowallus** [comment]
Hi,
thanks for writing. No, I have not compiled PgSA for a long time :). I hope I will find a time, test it on recent gcc and maybe update building to CMake.

**Comment by morispi** [comment]
Hi,

Thanks for the fast answer, and sorry for taking so long to answer back. I have developed a long read error correction tool that relies on PgSA, so until you do find time, is it fine if I attach a patched version of the aforementioned files to my project, so it can compile on recent gcc? I am a PhD student, so, no commercial purposes obviously.

Also, the PgSA paper states that a future version of the algorithm will support querying with multiple threads. I know the paper is a bit old, but is this new version still being considered?

**Comment by kowallus** [comment]
Hi,
I see if you will attach a patched PgSA version to your project. If you want you can also fork and propose a fix to the original repo. Currently, we are not planning on development (too little interest and users), but if you want you can always contribute to multiple threads feature ;). However, as long as I remember, parallelization is not extremely straightforward (though it should not be very hard).

**Comment by kowallus** [comment]
I commited a fix. Can you check if it works?

**Comment by morispi** [comment]
It does work fine indeed. :) Thank you!
